app/blueprints/multilingual/routes.py
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 30 13:22:16 2020

@author: PAVA
"""
#import cv2
import os
import datetime
import hashlib, binascii
import random
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    make_response,
    session,
    Blueprint,
    g
)
from flask_login import (
    LoginManager,
    UserMixin,
    login_user,
    login_required,
    logout_user,
    current_user
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine 
from sqlalchemy.orm import sessionmaker 
from sqlalchemy import Column, Integer, String
from flask_sqlalchemy import SQLAlchemy
from flask_babel import _, refresh
from app import app
import config as c
import random

multilingual = Blueprint('multilingual', __name__, template_folder='templates')

# Database info
server = c.server
database = c.database
login = c.uid
passwd = c.password
driver = c.driver

# Global vars
rtls_tag_identifier = c.rtls_tag_identifier
scaling_factor_x = c.scaling_factor_x
scaling_factor_y = c.scaling_factor_y
x_prefix = c.x_prefix
y_prefix = c.x_prefix

# Choose version of locate
version = c.version

# Init of flask object
app.secret_key = c.secret_key

# MS Sql
app.config['SQLALCHEMY_DATABASE_URI'] = 'mssql://{}:{}@{}/{}?driver={}'.format(login,passwd,server,database,driver)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.init_app(app)

def hash_password(password):
    # Hash a password for storing in db
    salt = hashlib.sha256(os.urandom(60)).hexdigest().encode('ascii')
    pwdhash = hashlib.pbkdf2_hmac('sha512', password.encode('utf-8'), 
                                salt, 100000)
    pwdhash = binascii.hexlify(pwdhash)
    return (salt + pwdhash).decode('ascii')

def get_lang():
    if 'lang' in session and session.get('lang'):
        g.lang_code = session.get('lang')
        print('jazyk je en')
    else:
        g.lang_code = 'de'
        print('jazyk je sk')
    return g.lang_code


def verify_password(stored_password, provided_password):
    """Verify a stored password against one provided by user"""
    salt = stored_password[:64]
    stored_password = stored_password[64:]
    pwdhash = hashlib.pbkdf2_hmac('sha512', 
                                  provided_password.encode('utf-8'), 
                                  salt.encode('ascii'), 
                                  100000)
    pwdhash = binascii.hexlify(pwdhash).decode('ascii')
    return pwdhash == stored_password

class users(UserMixin, db.Model):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(50),unique=True)
    password = db.Column(db.String(500))

    def __init__(self,username, password):
        self.username = username
        self.password = password

class rtls_tags(db.Model):
    row_no = db.Column(db.Integer,primary_key=True)
    tag_id=db.Column(db.String(50))
    address=db.Column(db.String(50))
    PosX=db.Column(db.Float())
    PosY=db.Column(db.Float())
    zone_id=db.Column(db.String(50))
    zone_type=db.Column(db.String(50))
    zone_name=db.Column(db.String(50))
    zone_enter=db.Column(db.DateTime())
    paired=db.Column(db.Integer)
    paired_id=db.Column(db.String(50))

    def __init__(self,tag_id,object_id,edited_by):
        self.row_no=row_no
        self.tag_id=tag_id
        self.address=address
        self.PosX=PosX
        self.PosY=PosY
        self.zone_id=zone_id
        self.zone_type=zone_type
        self.zone_name=zone_name
        self.zone_enter=zone_enter
        self.paired=paired
        self.paired_id=paired_id

class logs(db.Model):
    row_no = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(50))
    type_of_change = db.Column(db.String(50))
    tag_id=db.Column(db.String(50))
    object_id=db.Column(db.String(50))

    def __init__(self,username,type_of_change,tag_id,object_id):
        self.username=username
        self.type_of_change=type_of_change
        self.tag_id=tag_id
        self.object_id=object_id

class tag_location(db.Model):
    row_no = db.Column(db.Integer,primary_key=True)
    tag_id=db.Column(db.String(50))
    x=db.Column(db.Integer)
    y=db.Column(db.Integer)

    def __init__(self,username,type_of_change,tag_id,object_id):
        self.tag_id=tag_id
        self.object_id=object_id

@login_manager.user_loader
def load_user(user_id):
    return users.query.get(int(user_id))

# Login page
@multilingual.route('/',methods=['GET','POST'])
def login():
    g.lang_code = get_lang()
    if request.method =='POST':
        username = request.form['username']
        password = request.form['password']
        user = users.query.filter_by(username=username).first()
        if user:
            vp = True
            vp = verify_password(user.password, password)
            if vp:
                login_user(user)
                return redirect(url_for('multilingual.Index'))
    return render_template('multilingual/login.html')


# Function returns tag data for location if the tag is in db
def get_tag_info(tag_id):
    tag_id=tag_id.upper()
    my_data_parsed=[]
    if tag_id.startswith(rtls_tag_identifier):
        my_data= db.session.query(rtls_tags).filter_by(tag_id=tag_id).first()
    else:
        my_data= db.session.query(rtls_tags).filter_by(paired_id=tag_id).first()
    
    # if my_data is None:

    #     #########################################
    #     try:
    #         dbcitosession = create_session()
    #         data = dbcitosession.query(tERPOrders).filter(tERPOrders.OrderSign==tag_id).first()
    #         dbcitosession.commit()
    #     except:
    #         dbcitosession.rollback()
    #     finally:
    #         dbcitosession.close()
    #     #########################################

    #     if data is None:
    #         return False,my_data_parsed
    #     else : 
    #         tag_id = str(data.Order_RId) + '-000000'
    #         my_data = db.session.query(rtls_tags).filter_by(paired_id=tag_id).first()
    
    if my_data is None:
        return False,my_data_parsed
   
    else:
        # if 'my_data' in session:
        #     session.pop('my_data', None)
        my_data_parsed.append( [my_data.tag_id,
                my_data.zone_id,
                my_data.zone_type,
                my_data.zone_name,
                my_data.zone_enter,
                my_data.paired_id,
                float(my_data.PosX),
                float(my_data.PosY)])
        return True,my_data_parsed


@app.login_manager.unauthorized_handler
def unauth_handler():
    return redirect(url_for('multilingual.login'))


# Logout button
@multilingual.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('multilingual.login'))

# RTLS Control page
@multilingual.route('/rtls_control')
@login_required
def Index():
    # Get all paired tags and render page with them
    try:
        i=request.args['i']
    except:
        i = 0
    try:
        code1=request.args['code1']
        code2=request.args['code2']
    except:
        code1 = 0
        code2 = 0

    if current_user.username in c.users:
        dsb="disabled"
    else:
        dsb=""

    g.lang_code = get_lang()

    # if 'my_data' in session and session.get('my_data'):
    #     mydata = session.get('my_data')
    #     tag_id=mydata[0][0]
    #     got_data,mydata=get_tag_info(tag_id)
    #     if got_data:
    #         mydata[0][6]= (mydata[0][6] + x_prefix) * scaling_factor_x 
    #         mydata[0][7]= (mydata[0][7] + y_prefix) * scaling_factor_y
    #         session['my_data']=mydata
    #         #################################################################
    #         #return render_template('multilingual/locate.html',mydata=mydata)
    #         ################################################################
    #     else:
    #         flash(_('Tag %(tag_id)s sa v databáze nenachádza', tag_id =tag_id), "error")
    # else:
    #     mydata=0

    return render_template('multilingual/Index.html',
                           user= current_user.username,
                           dsb=dsb,i=int(i),
                           code1=code1,
                           code2=code2,
                           mydata=0)


# Pair tag form
@multilingual.route('/insert',methods=['POST'])
def insert():
    g.lang_code = get_lang()
    if request.method == 'POST':
        tag_id = request.form['tag_id']
        tag_id = tag_id.upper()
        object_id = request.form['object_id']
        object_id = object_id.upper()
        tags =[]
        # One of barcodes has to start with RTLS identifier
        condition1 = tag_id.startswith(rtls_tag_identifier)
        condition2 = object_id.startswith(rtls_tag_identifier)
        if condition1:
            tags=[tag_id,object_id]
        elif condition2 :
            tags=[object_id,tag_id]

        # If fields are blank or conditions are not met
        if not (tag_id
            and object_id
            and (condition1 + condition2 == 1)
            ):
            flash(_('Nesprávne zadané vstupné dáta'), "error")
            return redirect(url_for('multilingual.Index'))

        # Condition 3 tag exists in database and is not paired
        condition3 = db.session.query(rtls_tags.paired).filter_by(tag_id=tags[0]).first()
        # Condition 4 object is not paired with tag
        condition4 = db.session.query(rtls_tags.paired_id).filter_by(paired_id=tags[1]).first()

        # If return is not none the tag does not exist in db
        if condition3 is None:
            flash(_('Tag sa v databáze nenachádza'), "error")
            return redirect(url_for('multilingual.Index'))
        
        # If tag is paired
        if condition3[0]:
            flash(_('Tag je už spárovaný'), "error")
            return redirect(url_for('multilingual.Index',i=1,code1=tags[0],code2=tags[1]))
        

app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- stylesheets -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index_new_css.css') }}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    {% if i == 1 %}
    <script>
        $(document).ready(function(){
            $("#preparovanie").modal('show');
        });
    </script>
    {% endif %}

    {% if i == 2 %}
    <!-- <meta http-equiv="refresh" content="1"> -->
    <script type="text/javascript">
    var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    <script>
    function get_new_data() { 
        $.getJSON(
               $SCRIPT_ROOT + "_get_new_data",
               function (data) {
               $('#PosX').text(data.PosX);
           }   
       );    
    }
    setInterval('get_new_data',1000);
    </script>

    <script>
        $(document).ready(function(){
            $("#locate").modal('show');
        });
    </script>
    {% endif %}

    <title>{% block title %} {% endblock %}</title>
    <link rel = "icon" href = "{{ url_for('static',filename='logo.png') }}" type = "image/x-icon">
    </head>
    <body>
      {%include 'navbar.html'%}
      <br>
      </br>

{% block body %}
{% endblock %}

<!-- forma na parovanie tagov -->
<div id="mymodal" class="modal fade" role = "dialog" tabindex="-1">
                <div class= "modal-dialog modal-dialog-centered">
                <div class= "modal-content">
                    <div class= "modal-header">

                        <h4 class="modal-title">{{_('Spárovať tag')}}</h4>
                    </div>
                    <div class="modal-body">

                        <form action ="{{url_for('multilingual.insert')}}" method="POST">


                        <div class="form-group">
                            <label>{{_('Čiarový kód')}} 1</label>
                            <input type="text" onClick="this.setSelectionRange(0, this.value.length)" class="form-control" name="tag_id" required="1" >

                        </div>

                        <div class="form-group">
                            <label>{{_('Čiarový kód')}} 2</label>
                            <input type="text" onClick="this.setSelectionRange(0, this.value.length)" class="form-control" name="object_id" required="1">

                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">{{_('Spárovať tag')}}</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{_('Zavrieť')}}</button>
                        </div>

                        </form>
                    </div>
                  </div>
                </div>
              </div>
<!-- forma na parovanie tagov -->

<!-- forma na odparovanie tagov -->
<div id="mymodal1" class="modal fade" role = "dialog" tabindex="-1">
  <div class= "modal-dialog modal-dialog-centered">
  <div class= "modal-content">
      <div class= "modal-header">

          <h4 class="modal-title">{{_('Odpárovať tag')}}</h4>
      </div>
      <div class="modal-body">

          <form action ="{{url_for('multilingual.unpair')}}" method="POST">

          <div class="form-group">
              <label>{{_('RTLS Tag ID')}}</label>
              <input type="text" onClick="this.setSelectionRange(0, this.value.length)" class="form-control" name="tag_id" required="1">

          </div>


          <div class="form-group">
              <button class="btn btn-primary" type="submit">{{_('Odpárovať tag')}}</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{{_('Zavrieť')}}</button>
          </div>

          </form>

      </div>
    </div>
  </div>
</div>
<!-- forma na odparovanie tagov -->


<!-- Forma na lokalizáciu -->
<div id="mymodal5" class="modal fade" role = "dialog"  tabindex="-1">
  <div class= "modal-dialog modal-dialog-centered">
  <div class= "modal-content">
      <div class= "modal-header">

      <h4 class="modal-title">{{_('Lokalizácia tagu')}}</h4>
      </div>
      <div class="modal-body">

          <form action ="{{url_for('multilingual.locate')}}" method="POST">

          <div class="form-group">
              <label>{{_('Čiarový kód')}}</label>
              <input type="text" onClick="this.setSelectionRange(0, this.value.length)" class="form-control" name="tag_id" required="1">

          </div>


          <div class="form-group">
              <button class="btn btn-primary" type="submit">{{_('Lokalizovať')}}</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{{_('Zavrieť')}}</button>
          </div>

          </form>

      </div>
    </div>
  </div>
</div>
<!--Forma na lokalizáciu-->

<!-- Forma na lokalizáciu -->
<div id="mymodal6" class="modal fade" role = "dialog"  tabindex="-1">
  <div class= "modal-dialog modal-dialog-centered">
  <div class= "modal-content">
      <div class= "modal-header">

      <h4 class="modal-title">{{_('Lokalizácia skupiny tagov')}}</h4>
      </div>
      <div class="modal-body">

          <form action ="{{url_for('multilingual.locate_multiple')}}" method="POST">

          <div class="form-group">
              <label>{{_('Zadajte skupinu kódov')}}</label>
              <input type="text" onClick="this.setSelectionRange(0, this.value.length)" class="form-control" name="tag_id" required="1">
          </div>

          <div class="form-group">
              <button class="btn btn-primary" type="submit">{{_('Lokalizovať')}}</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{{_('Zavrieť')}}</button>
          </div>

          </form>

      </div>
    </div>
  </div>
</div>
<!--Forma na lokalizáciu-->



<!-- Forma na preparovanie -->
{%if i ==1%}
<div id="preparovanie" class="modal fade" role = "dialog"  tabindex="-1" data-keyboard="false" data-backdrop="static">
  <div class= "modal-dialog modal-dialog-centered">
  <div class= "modal-content">
      <div class= "modal-header">

          <h4 class="modal-title">{{_('Prepárovanie tagu')}}</h4>
      </div>
      <div class="modal-body">

          <form action ="{{url_for('multilingual.change_pair')}}" method="POST" >

          <div class="form-group">

              <p>{{_('Zadaný kód')}} <b>{{code1}}</b> {{_('je už spárovaný. Chcete ho prepárovať s vami zadaným kódom')}} <b>{{code2}}</b> :<p>

          </div>


          <div class="form-group">
              <button class="btn btn-primary" name="yes" value={{code1}}$,${{code2}} type="submit">{{_('Áno')}}</button>
              <button class="btn btn-primary" name="yes"  value= "nie" type="submit">{{_('Nie')}}</button>
          </div>

          </form>


      </div>
    </div>
  </div>
</div>
{% endif %}
<!--Forma na preparovanie-->

<!-- java scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  </body>
</html>

app/templates/navbar.html
<nav class="navbar sticky-top navbar-expand-md  navbar-light bg-light">
    <div class="container-fluid">

      <a href="https://sovagroup.sk/"><img src="{{ url_for('static',filename= 'sova_group.png') }}" style = 'height:38px' alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto ">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('multilingual.Index')}}">Domov</a>
          </li>
        </ul>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('multilingual.contact')}}">Kontakt</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <span class="navbar-text" style="padding-right: 10px; color: black">
              Prihlasený užívateľ: <strong>{{user}}</strong>
            </span>
         <a href="{{url_for('multilingual.logout')}}"> 
        <button class="btn btn-outline-danger" type="button">Odhlásenie</button></a>
      </li>
      </ul>

      </div>
    </div>
  </nav>